version: '3'
services:
  nosql:
    container_name: nosql
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=80
      - VIRTUAL_HOST=nosql.docker
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "8081:80"
    command: ['/bin/boot.sh']